const params=new URLSearchParams(location.search),token=params.get("token")||"",apiBase=`${location.protocol}//${location.hostname}:8011/api/engineer-task-access`;let access=null;
const escapeText=text=>String(text??"-").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const localTime=text=>text?new Intl.DateTimeFormat("zh-TW",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Taipei"}).format(new Date(text)):"-";
async function request(path,options={}){const response=await fetch(`${apiBase}${path}`,{...options,headers:{Authorization:`Bearer ${token}`,...(options.headers||{})}});const text=await response.text();let body={};try{body=text?JSON.parse(text):{};}catch{body={detail:text};}if(!response.ok)throw new Error(body.detail||"Request failed");return body;}
function showError(error){document.getElementById("errorPanel").classList.remove("hidden");document.getElementById("errorPanel").textContent=`無法開啟任務：${error.message}`;document.getElementById("pageStatus").textContent="連結無效或已過期";}
function render(){const task=access.task,a=access.currentAssignee;document.getElementById("pageStatus").textContent=`登入身分：${a.engineerName}`;["taskPanel","reportsPanel","timelinePanel"].forEach(id=>document.getElementById(id).classList.remove("hidden"));document.getElementById("workflowBadge").textContent=task.workflowStatus;document.getElementById("taskTitle").textContent=`${task.stationName} / ${task.issue}`;document.getElementById("taskSummary").innerHTML=`<dt>Task ID</dt><dd class="mono">${escapeText(task.taskId)}</dd><dt>批次</dt><dd>${escapeText(task.batchLabel||task.batchId)}</dd><dt>風險</dt><dd>${escapeText(task.level)}</dd><dt>建議</dt><dd>${escapeText(task.recommendation)}</dd>`;document.getElementById("assigneeList").innerHTML=(task.assignees||[]).map(x=>`<article><strong>${x.isPrimary?"Primary":"Collaborator"}：${escapeText(x.engineerName)}</strong><p>${x.isRequiredParticipant?"必要參與者":"非必要參與者"}</p><p>${x.acknowledgedAt?`已 ACK ${localTime(x.acknowledgedAt)}`:"尚未 ACK"}</p></article>`).join("");document.getElementById("reportList").innerHTML=(task.reports||[]).map(r=>`<article class="report-card"><strong>${escapeText(r.reportType)} / ${localTime(r.reportedAt)}</strong><p>觀察：${escapeText(r.observedCondition)}</p><p>處置：${escapeText(r.actionTaken)}</p><p>結果：${escapeText(r.resultDescription)}</p></article>`).join("")||"尚無回報";document.getElementById("timelineList").innerHTML=(access.timeline||[]).map(e=>`<li><strong>${escapeText(e.eventType)}</strong><span>${localTime(e.eventTime)} / ${escapeText(e.actorName||e.actorType)}</span><p>${escapeText(e.message||"")}</p></li>`).join("");const completed=task.workflowStatus==="completed",submitted=task.workflowStatus==="completion_submitted";document.getElementById("ackButton").disabled=Boolean(a.acknowledgedAt)||completed;document.getElementById("startButton").disabled=!a.acknowledgedAt||task.workflowStatus!=="acknowledged";document.getElementById("completeButton").disabled=!a.isPrimary||task.workflowStatus!=="in_progress";const canSupplement=completed&&task.supplementationOpen&&a.supplementationAllowed;document.getElementById("reportPanel").classList.toggle("hidden",completed&&!canSupplement);if(submitted)document.getElementById("reportPanel").querySelector("h2").textContent="新增提交後補充回報";}
async function reload(){access=await request("/task");render();}
async function action(path,body={}){access=await request(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});render();}
document.getElementById("ackButton").onclick=()=>action("/ack",{}).catch(showError);document.getElementById("startButton").onclick=()=>action("/start",{}).catch(showError);document.getElementById("completeButton").onclick=()=>{if(confirm("確認提交整體完成，交由 Manager 驗收？"))action("/completion-submit",{}).catch(showError);};
document.getElementById("reportForm").onsubmit=async event=>{event.preventDefault();try{const report=await request("/reports",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({observedCondition:document.getElementById("observedCondition").value,confirmedCause:document.getElementById("confirmedCause").value||null,actionTaken:document.getElementById("actionTaken").value,resultDescription:document.getElementById("resultDescription").value,remainingIssue:document.getElementById("remainingIssue").value||null,note:document.getElementById("reportNote").value||null})});const files=[...document.getElementById("reportFiles").files];if(files.length>5)throw new Error("每次最多 5 張照片");if(files.length){const form=new FormData();files.forEach(file=>form.append("files",file));const response=await fetch(`${apiBase}/reports/${report.reportId}/attachments`,{method:"POST",headers:{Authorization:`Bearer ${token}`},body:form});if(!response.ok){const body=await response.json();throw new Error(body.detail||"照片上傳失敗");}}event.target.reset();await reload();}catch(error){showError(error);}};
reload().then(()=>{if(params.get("action")==="ack"&&!access.currentAssignee.acknowledgedAt)return action("/ack",{});}).catch(showError);
